### ISSUE TITLE
Complain about missing gschema in latest elementary OS Odin daily

### ISSUE THREAD

**Issue by hanaral** [sapoturge/froggum#11]
Great work on the app, but I can't seem to start it. It complains the about the gschema.xml file being missing when it clearly isn't. maybe there is a directory change in Odin that I'm not aware of.

Here's the terminal ouput if it's of any help:

```
~$ com.github.sapoturge.froggum 

(process:18973): GLib-GIO-ERROR **: 09:16:49.236: Settings schema 'com.github.sapoturge.froggum' is not installed
Trace/breakpoint trap
```

**Comment by sapoturge** [comment]
The file is installed, but you have to run `glib-compile-schemas` before it can be used. Code does it in `post_install.py`, so I'll add it there soon.

**Comment by sapoturge** [comment]
For some reason Travis isn't able to run post_install.py in the test. Can you try installing from the bugfix-install-schema branch and tell me if it works for you?

**Comment by hanaral** [comment]
The fix seems to have worked.
