### ISSUE TITLE
Switches in the sidebar are oversized

### ISSUE THREAD

**Issue by hanaral** [sapoturge/froggum#14]
If I understand correcly, the object boxes are supposed to resize based on the size of said object. It seems that the visibility switches scale with them
![Screenshot from 2020-09-01 21-29-23](https://user-images.githubusercontent.com/58219504/91902912-4f6ec680-ec9a-11ea-9972-ce9c3e55e873.png)

**Comment by sapoturge** [comment]
Yes, the entire row scales up to match the icon view. In the new feature-update-ui branch, I'm fixing the height of the icon view to 32px (which will be probably be made variable in a future release), which looks more reasonable.
